site_name: MkDocs Material 文档
site_url: https://mingminyu.github.io/mkdocs-material
site_author: Mingmin Yu
site_description: >-
  MkDocs Material 中文文档

repo_name: mingminyu/mkdocs-material
repo_url: https://github.com/mingminyu/mkdocs-material

copyright: Copyright &copy; 2024

theme:
  name: material
  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tooltips
    - content.tabs.link
    - content.footnote.tooltips
    - navigation.footer
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-6
        name: 暗黑模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: 明亮模式

  favicon: assets/favicon.png
  icon:
    logo: logo
  
  language: zh

plugins:
  - tags
  - blog
  # - toggle-sidebar
  - tags:
      enabled: true
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

extra:
  status:
    new: Recently added
    deprecated: Deprecated
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mingminyu
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/mkdocs-material/
    

markdown_extensions:
  - abbr
  - tables
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - 入门:
    - 安装: index.md
    - 新建网站: getting-started/create-your-site.md
    - 发布网站: getting-started/public-your-site.md
    - 自定义: getting-started/customization.md
    - 约定: getting-started/conventions.md
    - 浏览器支持: getting-started/browser-support.md
    - 企业反馈: getting-started/enterprise-support.md
    - 哲学: getting-started/philosophy.md
    - 备选方案: getting-started/alternatives.md
    - 许可: getting-started/license.md
    - 教程:
        - tutorials/index.md
        - "博客":
            - 基础: tutorials/blogs/basic.md
            - 导航: tutorials/blogs/navigation.md
            - 参与和内容传播: tutorials/blogs/engage.md
        - "社交卡片":
            - tutorials/social/basic.md
            - tutorials/social/custom.md
    - "更改日志":
        - changelog/index.md
        - 升级: upgrade.md

  - 设置:
    - setup/index.md
    - 更改颜色: setup/changing-the-colors.md
    - 更改字体: setup/changing-the-fonts.md
    - 扩展:
        - enumerate-headings-plugin: setup/extensions/mkdocs-enumerate-headings-plugin.md
        - toggle-sidebar-plugin: setup/extensions/mkdocs-toggle-sidebar-plugin.md
  